name: catweb_parser
description: A new flutter plugin project.
version: 0.0.8
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^4.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.example.catweb_parser
        pluginClass: CatwebParserPlugin
      ios:
        pluginClass: CatwebParserPlugin
      windows:
        pluginClass: CatwebParserPlugin

ffigen:
  output: 'lib/gen/h/libgo.h.dart'
  headers:
    entry-points:
      - 'lib/libs/libgo.h'